// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

import proto "google.golang.org/protobuf/proto"

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTime int64 `protobuf:"varint,1,opt,name=ClientTime,json=clientTime,proto3" json:"ClientTime,omitempty"` //客户端时间戳
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *Ping) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *Ping) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *Ping) SetClientTime(val int64) {
	if x != nil {
		x.ClientTime = val
	}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime int64 `protobuf:"varint,1,opt,name=ServerTime,json=serverTime,proto3" json:"ServerTime,omitempty"` //服务器本地时间戳
	ClientTime int64 `protobuf:"varint,2,opt,name=ClientTime,json=clientTime,proto3" json:"ClientTime,omitempty"` //客户端时间戳
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *Pong) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *Pong) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *Pong) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *Pong) SetServerTime(val int64) {
	if x != nil {
		x.ServerTime = val
	}
}
func (x *Pong) SetClientTime(val int64) {
	if x != nil {
		x.ClientTime = val
	}
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   string `protobuf:"bytes,1,opt,name=AppId,json=appId,proto3" json:"AppId,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"Token,omitempty"`
	IsDebug bool   `protobuf:"varint,3,opt,name=IsDebug,json=isDebug,proto3" json:"IsDebug,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *Login) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *Login) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdkLogin.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Login) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Login) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Login) GetIsDebug() bool {
	if x != nil {
		return x.IsDebug
	}
	return false
}

func (x *Login) SetAppId(val string) {
	if x != nil {
		x.AppId = val
	}
}
func (x *Login) SetToken(val string) {
	if x != nil {
		x.Token = val
	}
}
func (x *Login) SetIsDebug(val bool) {
	if x != nil {
		x.IsDebug = val
	}
}

type LoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ERROR_CODE `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.ERROR_CODE" json:"Result,omitempty"`
	RoomId string     `protobuf:"bytes,2,opt,name=RoomId,json=roomId,proto3" json:"RoomId,omitempty"`
	UID      string     `protobuf:"bytes,3,opt,name=UID,json=uID,proto3" json:"UID,omitempty"`
	NickName string     `protobuf:"bytes,4,opt,name=NickName,json=nickName,proto3" json:"NickName,omitempty"`
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *LoginResult) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *LoginResult) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResult) GetResult() ERROR_CODE {
	if x != nil {
		return x.Result
	}
	return ERROR_CODE_SUCCESS
}

func (x *LoginResult) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LoginResult) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *LoginResult) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *LoginResult) SetResult(val ERROR_CODE) {
	if x != nil {
		x.Result = val
	}
}
func (x *LoginResult) SetRoomId(val string) {
	if x != nil {
		x.RoomId = val
	}
}
func (x *LoginResult) SetUID(val string) {
	if x != nil {
		x.UID = val
	}
}
func (x *LoginResult) SetNickName(val string) {
	if x != nil {
		x.NickName = val
	}
}

type PlayStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayStart) Reset() {
	*x = PlayStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *PlayStart) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *PlayStart) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*PlayStart) ProtoMessage() {}

func (x *PlayStart) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayStart.ProtoReflect.Descriptor instead.
func (*PlayStart) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type PlayStartResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ERROR_CODE `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.ERROR_CODE" json:"Result,omitempty"`
}

func (x *PlayStartResult) Reset() {
	*x = PlayStartResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayStartResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *PlayStartResult) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *PlayStartResult) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*PlayStartResult) ProtoMessage() {}

func (x *PlayStartResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayStartResult.ProtoReflect.Descriptor instead.
func (*PlayStartResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *PlayStartResult) GetResult() ERROR_CODE {
	if x != nil {
		return x.Result
	}
	return ERROR_CODE_SUCCESS
}

func (x *PlayStartResult) SetResult(val ERROR_CODE) {
	if x != nil {
		x.Result = val
	}
}

type PlayEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlayEnd) Reset() {
	*x = PlayEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *PlayEnd) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *PlayEnd) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*PlayEnd) ProtoMessage() {}

func (x *PlayEnd) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayEnd.ProtoReflect.Descriptor instead.
func (*PlayEnd) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

type PlayEndResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ERROR_CODE `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.ERROR_CODE" json:"Result,omitempty"`
}

func (x *PlayEndResult) Reset() {
	*x = PlayEndResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayEndResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *PlayEndResult) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *PlayEndResult) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*PlayEndResult) ProtoMessage() {}

func (x *PlayEndResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayEndResult.ProtoReflect.Descriptor instead.
func (*PlayEndResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *PlayEndResult) GetResult() ERROR_CODE {
	if x != nil {
		return x.Result
	}
	return ERROR_CODE_SUCCESS
}

func (x *PlayEndResult) SetResult(val ERROR_CODE) {
	if x != nil {
		x.Result = val
	}
}

type Report struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []*ReportInfo `protobuf:"bytes,1,rep,name=Info,json=info,proto3" json:"Info,omitempty"`
}

func (x *Report) Reset() {
	*x = Report{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *Report) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *Report) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *Report) GetInfo() []*ReportInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Report) SetInfo(val []*ReportInfo) {
	if x != nil {
		x.Info = val
	}
}

type ReportResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ERROR_CODE      `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.ERROR_CODE" json:"Result,omitempty"`
	Info   []*AudienceInfo `protobuf:"bytes,2,rep,name=Info,json=info,proto3" json:"Info,omitempty"`
}

func (x *ReportResult) Reset() {
	*x = ReportResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *ReportResult) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *ReportResult) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*ReportResult) ProtoMessage() {}

func (x *ReportResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResult.ProtoReflect.Descriptor instead.
func (*ReportResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *ReportResult) GetResult() ERROR_CODE {
	if x != nil {
		return x.Result
	}
	return ERROR_CODE_SUCCESS
}

func (x *ReportResult) GetInfo() []*AudienceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ReportResult) SetResult(val ERROR_CODE) {
	if x != nil {
		x.Result = val
	}
}
func (x *ReportResult) SetInfo(val []*AudienceInfo) {
	if x != nil {
		x.Info = val
	}
}

type GetRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopCount int32 `protobuf:"varint,1,opt,name=TopCount,json=topCount,proto3" json:"TopCount,omitempty"`
}

func (x *GetRank) Reset() {
	*x = GetRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *GetRank) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *GetRank) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*GetRank) ProtoMessage() {}

func (x *GetRank) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRank.ProtoReflect.Descriptor instead.
func (*GetRank) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *GetRank) GetTopCount() int32 {
	if x != nil {
		return x.TopCount
	}
	return 0
}

func (x *GetRank) SetTopCount(val int32) {
	if x != nil {
		x.TopCount = val
	}
}

type GetRankResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ERROR_CODE  `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.ERROR_CODE" json:"Result,omitempty"`
	Info   []*Audience `protobuf:"bytes,2,rep,name=Info,json=info,proto3" json:"Info,omitempty"`
}

func (x *GetRankResult) Reset() {
	*x = GetRankResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *GetRankResult) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *GetRankResult) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*GetRankResult) ProtoMessage() {}

func (x *GetRankResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResult.ProtoReflect.Descriptor instead.
func (*GetRankResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *GetRankResult) GetResult() ERROR_CODE {
	if x != nil {
		return x.Result
	}
	return ERROR_CODE_SUCCESS
}

func (x *GetRankResult) GetInfo() []*Audience {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetRankResult) SetResult(val ERROR_CODE) {
	if x != nil {
		x.Result = val
	}
}
func (x *GetRankResult) SetInfo(val []*Audience) {
	if x != nil {
		x.Info = val
	}
}

//新用户推送
type NotifyNewAudience struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audience *Audience `protobuf:"bytes,1,opt,name=Audience,json=audience,proto3" json:"Audience,omitempty"`
}

func (x *NotifyNewAudience) Reset() {
	*x = NotifyNewAudience{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyNewAudience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *NotifyNewAudience) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *NotifyNewAudience) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*NotifyNewAudience) ProtoMessage() {}

func (x *NotifyNewAudience) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewAudience.ProtoReflect.Descriptor instead.
func (*NotifyNewAudience) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyNewAudience) GetAudience() *Audience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *NotifyNewAudience) SetAudience(val *Audience) {
	if x != nil {
		x.Audience = val
	}
}

//用户行为推送
type NotifyAudienceAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId  string `protobuf:"bytes,1,opt,name=OpenId,json=openId,proto3" json:"OpenId,omitempty"`     //ID
	Content string `protobuf:"bytes,2,opt,name=Content,json=content,proto3" json:"Content,omitempty"`  //评论
	LikeNum int32  `protobuf:"varint,3,opt,name=LikeNum,json=likeNum,proto3" json:"LikeNum,omitempty"` //点赞数量
	GiftId  string `protobuf:"bytes,4,opt,name=GiftId,json=giftId,proto3" json:"GiftId,omitempty"`     //礼物ID
	GiftNum int32  `protobuf:"varint,5,opt,name=GiftNum,json=giftNum,proto3" json:"GiftNum,omitempty"` //礼物数量
}

func (x *NotifyAudienceAction) Reset() {
	*x = NotifyAudienceAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyAudienceAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *NotifyAudienceAction) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *NotifyAudienceAction) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*NotifyAudienceAction) ProtoMessage() {}

func (x *NotifyAudienceAction) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyAudienceAction.ProtoReflect.Descriptor instead.
func (*NotifyAudienceAction) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyAudienceAction) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *NotifyAudienceAction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotifyAudienceAction) GetLikeNum() int32 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *NotifyAudienceAction) GetGiftId() string {
	if x != nil {
		return x.GiftId
	}
	return ""
}

func (x *NotifyAudienceAction) GetGiftNum() int32 {
	if x != nil {
		return x.GiftNum
	}
	return 0
}

func (x *NotifyAudienceAction) SetOpenId(val string) {
	if x != nil {
		x.OpenId = val
	}
}
func (x *NotifyAudienceAction) SetContent(val string) {
	if x != nil {
		x.Content = val
	}
}
func (x *NotifyAudienceAction) SetLikeNum(val int32) {
	if x != nil {
		x.LikeNum = val
	}
}
func (x *NotifyAudienceAction) SetGiftId(val string) {
	if x != nil {
		x.GiftId = val
	}
}
func (x *NotifyAudienceAction) SetGiftNum(val int32) {
	if x != nil {
		x.GiftNum = val
	}
}

//上报分数信息
type ReportInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId string `protobuf:"bytes,1,opt,name=OpenId,json=openId,proto3" json:"OpenId,omitempty"`
	Score  int32  `protobuf:"varint,2,opt,name=Score,json=score,proto3" json:"Score,omitempty"`
	IsWin  bool   `protobuf:"varint,3,opt,name=IsWin,json=isWin,proto3" json:"IsWin,omitempty"`
}

func (x *ReportInfo) Reset() {
	*x = ReportInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *ReportInfo) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *ReportInfo) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*ReportInfo) ProtoMessage() {}

func (x *ReportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInfo.ProtoReflect.Descriptor instead.
func (*ReportInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *ReportInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ReportInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReportInfo) GetIsWin() bool {
	if x != nil {
		return x.IsWin
	}
	return false
}

func (x *ReportInfo) SetOpenId(val string) {
	if x != nil {
		x.OpenId = val
	}
}
func (x *ReportInfo) SetScore(val int32) {
	if x != nil {
		x.Score = val
	}
}
func (x *ReportInfo) SetIsWin(val bool) {
	if x != nil {
		x.IsWin = val
	}
}

//观众信息
type Audience struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudienceBasic *AudienceBasic `protobuf:"bytes,1,opt,name=AudienceBasic,json=audienceBasic,proto3" json:"AudienceBasic,omitempty"` //观众基本信息
	AudienceInfo  *AudienceInfo  `protobuf:"bytes,2,opt,name=AudienceInfo,json=audienceInfo,proto3" json:"AudienceInfo,omitempty"`    //观众详细信息
}

func (x *Audience) Reset() {
	*x = Audience{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Audience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *Audience) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *Audience) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*Audience) ProtoMessage() {}

func (x *Audience) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audience.ProtoReflect.Descriptor instead.
func (*Audience) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *Audience) GetAudienceBasic() *AudienceBasic {
	if x != nil {
		return x.AudienceBasic
	}
	return nil
}

func (x *Audience) GetAudienceInfo() *AudienceInfo {
	if x != nil {
		return x.AudienceInfo
	}
	return nil
}

func (x *Audience) SetAudienceBasic(val *AudienceBasic) {
	if x != nil {
		x.AudienceBasic = val
	}
}
func (x *Audience) SetAudienceInfo(val *AudienceInfo) {
	if x != nil {
		x.AudienceInfo = val
	}
}

//观众基本信息
type AudienceBasic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId    string `protobuf:"bytes,1,opt,name=OpenId,json=openId,proto3" json:"OpenId,omitempty"`          //ID
	NickName  string `protobuf:"bytes,2,opt,name=NickName,json=nickName,proto3" json:"NickName,omitempty"`    //昵称
	AvatarUrl string `protobuf:"bytes,3,opt,name=AvatarUrl,json=avatarUrl,proto3" json:"AvatarUrl,omitempty"` //头像url
}

func (x *AudienceBasic) Reset() {
	*x = AudienceBasic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudienceBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *AudienceBasic) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *AudienceBasic) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*AudienceBasic) ProtoMessage() {}

func (x *AudienceBasic) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceBasic.ProtoReflect.Descriptor instead.
func (*AudienceBasic) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *AudienceBasic) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AudienceBasic) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AudienceBasic) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *AudienceBasic) SetOpenId(val string) {
	if x != nil {
		x.OpenId = val
	}
}
func (x *AudienceBasic) SetNickName(val string) {
	if x != nil {
		x.NickName = val
	}
}
func (x *AudienceBasic) SetAvatarUrl(val string) {
	if x != nil {
		x.AvatarUrl = val
	}
}

//观众详细信息
type AudienceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId        string `protobuf:"bytes,1,opt,name=OpenId,json=openId,proto3" json:"OpenId,omitempty"`                       //ID
	Score         int32  `protobuf:"varint,2,opt,name=Score,json=score,proto3" json:"Score,omitempty"`                         //总分
	Rank          int32  `protobuf:"varint,3,opt,name=Rank,json=rank,proto3" json:"Rank,omitempty"`                            //当前赛季排名
	LastRank      int32  `protobuf:"varint,4,opt,name=LastRank,json=lastRank,proto3" json:"LastRank,omitempty"`                //上赛季排名
	WinningStreak int32  `protobuf:"varint,5,opt,name=WinningStreak,json=winningStreak,proto3" json:"WinningStreak,omitempty"` //连胜
}

func (x *AudienceInfo) Reset() {
	*x = AudienceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudienceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (x *AudienceInfo) FromDB(data []byte) error {
	return proto.Unmarshal(data, x)
}

func (x *AudienceInfo) ToDB() ([]byte, error) {
	return proto.Marshal(x)
}

func (*AudienceInfo) ProtoMessage() {}

func (x *AudienceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInfo.ProtoReflect.Descriptor instead.
func (*AudienceInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *AudienceInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AudienceInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AudienceInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *AudienceInfo) GetLastRank() int32 {
	if x != nil {
		return x.LastRank
	}
	return 0
}

func (x *AudienceInfo) GetWinningStreak() int32 {
	if x != nil {
		return x.WinningStreak
	}
	return 0
}

func (x *AudienceInfo) SetOpenId(val string) {
	if x != nil {
		x.OpenId = val
	}
}
func (x *AudienceInfo) SetScore(val int32) {
	if x != nil {
		x.Score = val
	}
}
func (x *AudienceInfo) SetRank(val int32) {
	if x != nil {
		x.Rank = val
	}
}
func (x *AudienceInfo) SetLastRank(val int32) {
	if x != nil {
		x.LastRank = val
	}
}
func (x *AudienceInfo) SetWinningStreak(val int32) {
	if x != nil {
		x.WinningStreak = val
	}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x46,
	0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x49,
	0x73, 0x44, 0x65, 0x62, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x22, 0x80, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x3e, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x09, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x64,
	0x22, 0x3c, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x31,
	0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x66, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x29,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x25, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x63, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x42, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4e,
	0x65, 0x77, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x41, 0x75,
	0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x14, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x69, 0x66, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x69, 0x66, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x69, 0x66, 0x74, 0x4e, 0x75,
	0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x69, 0x66, 0x74, 0x4e, 0x75, 0x6d,
	0x22, 0x50, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x49, 0x73, 0x57, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x57,
	0x69, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x0d, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x0d,
	0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x39, 0x0a,
	0x0c, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x61, 0x75, 0x64, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x61, 0x0a, 0x0d, 0x41, 0x75, 0x64, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x92, 0x01, 0x0a, 0x0c,
	0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61,
	0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1a,
	0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x0d, 0x57, 0x69,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x77, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6b,
	0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_common_proto_goTypes = []interface{}{
	(*Ping)(nil),                 // 0: message.Ping
	(*Pong)(nil),                 // 1: message.Pong
	(*Login)(nil),                // 2: message.SdkLogin
	(*LoginResult)(nil),          // 3: message.LoginResult
	(*PlayStart)(nil),            // 4: message.PlayStart
	(*PlayStartResult)(nil),      // 5: message.PlayStartResult
	(*PlayEnd)(nil),              // 6: message.PlayEnd
	(*PlayEndResult)(nil),        // 7: message.PlayEndResult
	(*Report)(nil),               // 8: message.Report
	(*ReportResult)(nil),         // 9: message.ReportResult
	(*GetRank)(nil),              // 10: message.GetRank
	(*GetRankResult)(nil),        // 11: message.GetRankResult
	(*NotifyNewAudience)(nil),    // 12: message.NotifyNewAudience
	(*NotifyAudienceAction)(nil), // 13: message.NotifyAudienceAction
	(*ReportInfo)(nil),           // 14: message.ReportInfo
	(*Audience)(nil),             // 15: message.Audience
	(*AudienceBasic)(nil),        // 16: message.AudienceBasic
	(*AudienceInfo)(nil),         // 17: message.AudienceInfo
	(ERROR_CODE)(0),              // 18: message.ERROR_CODE
}
var file_common_proto_depIdxs = []int32{
	18, // 0: message.LoginResult.Result:type_name -> message.ERROR_CODE
	18, // 1: message.PlayStartResult.Result:type_name -> message.ERROR_CODE
	18, // 2: message.PlayEndResult.Result:type_name -> message.ERROR_CODE
	14, // 3: message.Report.Info:type_name -> message.ReportInfo
	18, // 4: message.ReportResult.Result:type_name -> message.ERROR_CODE
	17, // 5: message.ReportResult.Info:type_name -> message.AudienceInfo
	18, // 6: message.GetRankResult.Result:type_name -> message.ERROR_CODE
	15, // 7: message.GetRankResult.Info:type_name -> message.Audience
	15, // 8: message.NotifyNewAudience.Audience:type_name -> message.Audience
	16, // 9: message.Audience.AudienceBasic:type_name -> message.AudienceBasic
	17, // 10: message.Audience.AudienceInfo:type_name -> message.AudienceInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_msgtype_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayStartResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayEndResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Report); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyNewAudience); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyAudienceAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Audience); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudienceBasic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudienceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
